
reinstall_app true

devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5",
  "iPhone 4s"
])

languages([
  "en-US"
])

project "WaniKani.xcodeproj"
scheme "WaniKani"
app_identifier "com.haawa.WaniKani.debug"
